trigger:
- main

resources:
  repositories:
    - repository: gitops
      type: github
      name: mohdkhan0159/argocd-gitops
      endpoint: github

variables:
  imageName: python-argocd-app
  acrLoginServer: argocddemoacr123.azurecr.io
  tag: $(Build.BuildId)

pool:
  vmImage: ubuntu-latest

steps:

# Checkout Application Repo
- checkout: self

# Checkout GitOps Repo
- checkout: gitops
  persistCredentials: true

# Azure Login using Workload Identity Federation
# - task: AzureCLI@2
#   displayName: Azure Login
#   inputs:
#     azureSubscription: azure-azuredevops-28-02-2026
#     scriptType: bash
#     scriptLocation: inlineScript
#     inlineScript: |
#       az account show

# - script: |
#     echo "==== PRINTING DIRECTORY STRUCTURE ===="
#     echo "Build.SourcesDirectory = $(Build.SourcesDirectory)"
#     pwd
#     ls -la
#     echo "---- recursive ----"
#     ls -R
#   displayName: DEBUG - List Full Directory

# Build Docker Image
- task: Docker@2
  displayName: Build Image
  inputs:
    command: build
    repository: $(acrLoginServer)/$(imageName)
    dockerfile: $(System.DefaultWorkingDirectory)/python-argocd-app/Dockerfile
    tags: |
      $(tag)

# # Trivy Security Scan
# - script: |
#     sudo apt-get update
#     sudo apt-get install -y wget
#     wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Linux-64bit.deb
#     sudo dpkg -i trivy_0.50.0_Linux-64bit.deb
#     trivy image --exit-code 1 --severity HIGH,CRITICAL $(acrLoginServer)/$(imageName):$(tag)
#   displayName: Trivy Scan

# Push Image to Private ACR
# - task: Docker@2
#   displayName: Push Image
#   inputs:
#     command: push
#     repository: $(acrLoginServer)/$(imageName)
#     tags: |
#       $(tag)
#     containerRegistry: azure-azuredevops-28-02-2026

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-azuredevops-28-02-2026'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      # Login to ACR using Azure CLI (uses service principal behind azurerm connection)
      az acr login --name argocddemoacr123.azurecr.io

      # Build image
      docker build -t argocddemoacr123.azurecr.io/$(imageName):$(Build.BuildId) .

      # Push image
      docker push argocddemoacr123.azurecr.io/$(imageName):$(Build.BuildId)

# Update GitOps Manifest
- script: |
    cd $(System.DefaultWorkingDirectory)/argocd-gitops
    git checkout main
    cd dev

    echo "Updating image tag to $(tag)"

    sed -i "s|image:.*|image: $(acrLoginServer)/$(imageName):$(tag)|" deployment.yaml

    git config user.email "devops@demo.com"
    git config user.name "Azure DevOps"

    git add deployment.yaml
    git commit -m "Update image to $(tag)"
    git push origin main
  displayName: Update GitOps Repo
